# Generated by Django 2.0 on 2019-05-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190531_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precodois',
            name='preco',
            field=models.IntegerField(max_length=10, verbose_name='Preco Dois'),
        ),
        migrations.AlterField(
            model_name='precotres',
            name='preco',
            field=models.IntegerField(max_length=10, verbose_name='Preco Três'),
        ),
        migrations.AlterField(
            model_name='precoum',
            name='preco',
            field=models.IntegerField(max_length=10, verbose_name='Preco Um'),
        ),
    ]
