# Generated by Django 2.0 on 2019-05-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190531_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precodois',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='precotres',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='precoum',
            name='preco',
            field=models.IntegerField(),
        ),
    ]
