# Generated by Django 2.0 on 2019-05-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190531_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecoDois',
        ),
        migrations.DeleteModel(
            name='PrecoTres',
        ),
    ]
