# Generated by Django 2.0 on 2019-05-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190531_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoDois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrecoTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.IntegerField()),
            ],
        ),
    ]
