# Generated by Django 2.0 on 2019-05-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_precodois_precotres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precodois',
            old_name='preco',
            new_name='preco_dois',
        ),
        migrations.RenameField(
            model_name='precotres',
            old_name='preco',
            new_name='preco_tres',
        ),
        migrations.RenameField(
            model_name='precoum',
            old_name='preco',
            new_name='preco_um',
        ),
    ]
