# Generated by Django 2.0 on 2019-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190531_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAvancado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('preco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanoIntermediario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('preco', models.IntegerField()),
            ],
        ),
    ]
