# Generated by Django 2.0 on 2019-05-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_planoavancado_planointermediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planobasico',
            name='texto1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planobasico',
            name='texto2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planobasico',
            name='texto3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planobasico',
            name='texto4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planobasico',
            name='texto5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planobasico',
            name='texto6',
            field=models.TextField(blank=True),
        ),
    ]
