# Generated by Django 2.0 on 2019-05-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190531_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitulosdaPagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeirotitulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Primeiro Título')),
                ('texto1', models.TextField(blank=True, verbose_name='Primeira secao')),
                ('segundotitulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Título')),
                ('texto2', models.TextField(blank=True, verbose_name='Segunda secao')),
                ('terceirotitulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Terceiro Título')),
                ('texto3', models.TextField(blank=True, verbose_name='Terceira secao')),
                ('quartotitulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Quarto Título')),
                ('texto4', models.TextField(blank=True, verbose_name='Quarta secao')),
            ],
        ),
        migrations.AddField(
            model_name='planoavancado',
            name='texto1',
            field=models.TextField(blank=True, verbose_name='Texto1'),
        ),
        migrations.AddField(
            model_name='planoavancado',
            name='texto2',
            field=models.TextField(blank=True, verbose_name='Texto2'),
        ),
        migrations.AddField(
            model_name='planoavancado',
            name='texto3',
            field=models.TextField(blank=True, verbose_name='Texto3'),
        ),
        migrations.AddField(
            model_name='planoavancado',
            name='texto4',
            field=models.TextField(blank=True, verbose_name='Texto4'),
        ),
        migrations.AddField(
            model_name='planoavancado',
            name='texto5',
            field=models.TextField(blank=True, verbose_name='Texto5'),
        ),
        migrations.AddField(
            model_name='planoavancado',
            name='texto6',
            field=models.TextField(blank=True, verbose_name='Texto6'),
        ),
        migrations.AddField(
            model_name='planointermediario',
            name='texto1',
            field=models.TextField(blank=True, verbose_name='Texto1'),
        ),
        migrations.AddField(
            model_name='planointermediario',
            name='texto2',
            field=models.TextField(blank=True, verbose_name='Texto2'),
        ),
        migrations.AddField(
            model_name='planointermediario',
            name='texto3',
            field=models.TextField(blank=True, verbose_name='Texto3'),
        ),
        migrations.AddField(
            model_name='planointermediario',
            name='texto4',
            field=models.TextField(blank=True, verbose_name='Texto4'),
        ),
        migrations.AddField(
            model_name='planointermediario',
            name='texto5',
            field=models.TextField(blank=True, verbose_name='Texto5'),
        ),
        migrations.AddField(
            model_name='planointermediario',
            name='texto6',
            field=models.TextField(blank=True, verbose_name='Texto6'),
        ),
        migrations.AlterField(
            model_name='planobasico',
            name='texto1',
            field=models.TextField(blank=True, verbose_name='Texto1'),
        ),
        migrations.AlterField(
            model_name='planobasico',
            name='texto2',
            field=models.TextField(blank=True, verbose_name='Texto2'),
        ),
        migrations.AlterField(
            model_name='planobasico',
            name='texto3',
            field=models.TextField(blank=True, verbose_name='Texto3'),
        ),
        migrations.AlterField(
            model_name='planobasico',
            name='texto4',
            field=models.TextField(blank=True, verbose_name='Texto4'),
        ),
        migrations.AlterField(
            model_name='planobasico',
            name='texto5',
            field=models.TextField(blank=True, verbose_name='Texto5'),
        ),
        migrations.AlterField(
            model_name='planobasico',
            name='texto6',
            field=models.TextField(blank=True, verbose_name='Texto6'),
        ),
    ]
