# Generated by Django 2.0 on 2019-05-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190531_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulosdapagina',
            name='primeirotitulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Primeiro Título'),
        ),
        migrations.AlterField(
            model_name='titulosdapagina',
            name='quartotitulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Quarto Título'),
        ),
        migrations.AlterField(
            model_name='titulosdapagina',
            name='segundotitulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Título'),
        ),
        migrations.AlterField(
            model_name='titulosdapagina',
            name='terceirotitulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Terceiro Título'),
        ),
    ]
